# Generated by Django 5.0.6 on 2024-05-29 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_aluno', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, db_column='atualizado_em'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, db_column='criado_em', default=datetime.datetime.now),
            preserve_default=False,
        ),
    ]
