# Generated by Django 5.0.6 on 2024-05-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('nivel', models.CharField(blank=True, choices=[('T', 'Técnico'), ('G', 'Graduação'), ('P', 'Pós-Graduação')], max_length=1, null=True)),
                ('duracao', models.CharField(blank=True, max_length=50, null=True)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vagas_disponiveis', models.IntegerField(default=0)),
                ('certificacao', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False)),
                ('pre_requisitos', models.TextField(blank=True, null=True)),
                ('status_curso', models.CharField(default='Ativo', max_length=50)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'curso',
                'managed': True,
            },
        ),
    ]
