# Generated by Django 5.0.6 on 2024-05-28 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.CharField(blank=True, choices=[('Tec', 'Técnico'), ('Grad', 'Graduação'), ('Pos', 'Pós-Graduação')], null=True),
        ),
    ]
