# Generated by Django 5.0.6 on 2024-05-29 17:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cursos', '0002_alter_curso_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.CharField(blank=True, choices=[('Tec', 'Técnico'), ('Tecn', 'Tecnólogo'), ('Sup', 'Superior'), ('Pos', 'Pós-Graduação')], null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
    ]
