# Generated by Django 5.0.6 on 2024-05-31 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cursos', '0003_alter_curso_nivel_alter_curso_preco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ano_letivo', models.IntegerField()),
                ('periodo', models.CharField(choices=[('Integral', 'Integral'), ('Manha', 'Manha'), ('Tarde', 'Tarde'), ('Noite', 'Noite')], max_length=10)),
                ('sala', models.CharField(max_length=20)),
                ('professor_responsavel', models.CharField(max_length=100)),
                ('coord_curso', models.CharField(max_length=100)),
                ('email_coord', models.EmailField(max_length=100)),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'db_table': 'turma',
                'managed': True,
            },
        ),
    ]
